import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BarChart3, Boxes, LayoutDashboard, LogOut, Package, Plus, Shield, ShoppingCart, Trash2, Users, X } from 'lucide-react';
import { toast } from 'sonner';
import { api } from '@/services/api';
import { useAuth } from '@/contexts/AuthContext';

const nav = [
  ['dashboard', 'Dashboard', LayoutDashboard], ['products', 'Products', Package], ['users', 'Users', Users], ['sales', 'Sales', ShoppingCart], ['reports', 'Reports', BarChart3],
];

function Stat({ label, value }) { return <div className="rounded-2xl border border-border bg-surface p-5"><div className="text-xs uppercase tracking-[.12em] text-muted-foreground">{label}</div><div className="display mt-2 text-3xl text-foreground">{value}</div></div>; }
function Modal({ title, onClose, children }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm"><div className="w-full max-w-2xl rounded-3xl border border-border bg-surface p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="display text-3xl">{title}</h2><button onClick={onClose} className="rounded-full border border-border p-2"><X className="size-4" /></button></div><div className="mt-6">{children}</div></div></div>; }

export default function AdminDashboard() {
  const { user } = useAuth();
  const [section, setSection] = useState('dashboard');
  const [productModal, setProductModal] = useState(false);
  const queryClient = useQueryClient();
  const { data: dashboard } = useQuery({ queryKey: ['admin-dashboard'], queryFn: api.admin.dashboard });
  const { data: products = [] } = useQuery({ queryKey: ['admin-products'], queryFn: api.admin.products, enabled: section === 'products' });
  const { data: users = [] } = useQuery({ queryKey: ['admin-users'], queryFn: api.admin.users, enabled: section === 'users' });
  const { data: sales } = useQuery({ queryKey: ['admin-sales'], queryFn: api.admin.sales, enabled: section === 'sales' });
  const { data: reports } = useQuery({ queryKey: ['admin-reports'], queryFn: api.admin.reports, enabled: section === 'reports' });
  const deleteProduct = useMutation({ mutationFn: api.admin.deleteProduct, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['admin-products'] }); queryClient.invalidateQueries({ queryKey: ['admin-dashboard'] }); toast.success('Product deleted'); }, onError: (e) => toast.error(e.message) });
  const [form, setForm] = useState({ name: '', category: '', tagline: '', description: '', price: '', creator: '', initials: '', rating: '5', reviews: '0', install: '0', art: 'art-default', accent: '#d3a83f' });
  const createProduct = useMutation({ mutationFn: api.admin.createProduct, onSuccess: () => { setProductModal(false); queryClient.invalidateQueries({ queryKey: ['admin-products'] }); queryClient.invalidateQueries({ queryKey: ['admin-dashboard'] }); toast.success('Product created'); }, onError: (e) => toast.error(e.message) });
  const submitProduct = (e) => { e.preventDefault(); createProduct.mutate({ ...form, price: Number(form.price), rating: Number(form.rating), reviews: Number(form.reviews), install: String(form.install), features: [] }); };
  const title = useMemo(() => nav.find(([id]) => id === section)?.[1] || 'Dashboard', [section]);

  return <div className="min-h-screen bg-background text-foreground">
    <div className="flex min-h-screen">
      <aside className="hidden w-64 shrink-0 border-r border-border bg-surface p-5 lg:flex lg:flex-col"><div className="flex items-center gap-3 border-b border-border pb-5"><img src="/logo.png" alt="Cutting Edge Apps" className="size-10 object-contain" /><div><div className="font-semibold">Cutting Edge Apps</div><div className="text-xs text-muted-foreground">Admin Console</div></div></div><nav className="mt-6 space-y-1">{nav.map(([id, label, Icon]) => <button key={id} onClick={() => setSection(id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm ${section === id ? 'bg-[#d3a83f]/15 text-foreground' : 'text-muted-foreground hover:bg-surface-raised hover:text-foreground'}`}><Icon className="size-4" />{label}</button>)}</nav><div className="mt-auto rounded-2xl border border-border bg-surface-raised p-4"><div className="text-sm font-medium">{user?.name || 'Administrator'}</div><div className="text-xs text-muted-foreground">{user?.role}</div></div></aside>
      <main className="min-w-0 flex-1"><header className="flex items-center justify-between border-b border-border px-5 py-4 sm:px-8"><div><div className="text-xs uppercase tracking-[.14em] text-muted-foreground">Admin Console</div><h1 className="display mt-1 text-3xl sm:text-4xl">{title}</h1></div><div className="rounded-full border border-border px-3 py-1.5 text-xs text-muted-foreground">{user?.email}</div></header>
      <div className="p-5 sm:p-8">
        {section === 'dashboard' && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Products" value={dashboard?.stats?.products ?? '—'} /><Stat label="Users" value={dashboard?.stats?.users ?? '—'} /><Stat label="Orders" value={dashboard?.stats?.orders ?? '—'} /><Stat label="Revenue" value={dashboard ? `₹${Number(dashboard.stats.revenue || 0).toLocaleString('en-IN')}` : '—'} /></div><div className="mt-6 rounded-3xl border border-border bg-surface p-6"><h2 className="display text-2xl">Recent orders</h2><div className="mt-5 space-y-3">{(dashboard?.recentOrders || []).map((o) => <div key={o._id} className="flex items-center justify-between border-b border-border py-3 text-sm"><span>{o.customerEmail}</span><span>₹{Number(o.total || 0).toLocaleString('en-IN')}</span><span className="text-muted-foreground">{o.status}</span></div>)}</div></div></>}
        {section === 'products' && <div className="rounded-3xl border border-border bg-surface p-6"><div className="flex items-center justify-between"><div><h2 className="display text-2xl">Product catalogue</h2><p className="mt-1 text-sm text-muted-foreground">Create, update and remove marketplace apps.</p></div><button onClick={() => setProductModal(true)} className="btn-primary"><Plus className="size-4" /> Add product</button></div><div className="mt-6 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-border text-muted-foreground"><th className="py-3">Product</th><th>Category</th><th>Price</th><th>Sales</th><th></th></tr></thead><tbody>{products.map((p) => <tr key={p._id} className="border-b border-border"><td className="py-4 font-medium">{p.name}</td><td>{p.category}</td><td>₹{Number(p.price || 0).toLocaleString('en-IN')}</td><td>{p.salesCount || 0}</td><td className="text-right"><button onClick={() => deleteProduct.mutate(p._id)} className="rounded-lg p-2 text-[#ee9d83] hover:bg-[#ee9d83]/10" aria-label={`Delete ${p.name}`}><Trash2 className="size-4" /></button></td></tr>)}</tbody></table></div></div>}
        {section === 'users' && <div className="rounded-3xl border border-border bg-surface p-6"><h2 className="display text-2xl">Users</h2><div className="mt-6 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-border text-muted-foreground"><th className="py-3">Name</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody>{users.map((u) => <tr key={u._id} className="border-b border-border"><td className="py-4">{u.name}</td><td>{u.email}</td><td>{u.role}</td><td>{u.isActive ? 'Active' : 'Inactive'}</td></tr>)}</tbody></table></div></div>}
        {section === 'sales' && <div className="grid gap-4 sm:grid-cols-3"><Stat label="Revenue" value={`₹${Number(sales?.totalRevenue || 0).toLocaleString('en-IN')}`} /><Stat label="Paid orders" value={sales?.paidOrders ?? '—'} /><Stat label="Items sold" value={sales?.totalItems ?? '—'} /></div>}
        {section === 'reports' && <div className="grid gap-6 xl:grid-cols-2"><div className="rounded-3xl border border-border bg-surface p-6"><h2 className="display text-2xl">Top products</h2><div className="mt-5 space-y-3">{(reports?.topProducts || []).map((p) => <div key={String(p._id)} className="flex justify-between border-b border-border py-3 text-sm"><span>{p.name}</span><span>₹{Number(p.revenue || 0).toLocaleString('en-IN')}</span></div>)}</div></div><div className="rounded-3xl border border-border bg-surface p-6"><h2 className="display text-2xl">Daily sales</h2><div className="mt-5 space-y-3">{(reports?.byDay || []).map((d) => <div key={d._id} className="flex justify-between border-b border-border py-3 text-sm"><span>{d._id}</span><span>{d.orders} orders · ₹{Number(d.revenue || 0).toLocaleString('en-IN')}</span></div>)}</div></div></div>}
      </div></main></div>
    {productModal && <Modal title="Add product" onClose={() => setProductModal(false)}><form onSubmit={submitProduct} className="grid gap-4 sm:grid-cols-2">{[['name','Name'],['category','Category'],['tagline','Tagline'],['creator','Creator'],['initials','Initials'],['price','Price'],['description','Description'],['art','Artwork class']].map(([key,label]) => <label key={key} className="text-sm">{label}<input required={['name','category','tagline','creator','initials','price','description'].includes(key)} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} className="input-field mt-1" /></label>)}<button disabled={createProduct.isPending} className="btn-primary sm:col-span-2">{createProduct.isPending ? 'Creating...' : 'Create product'}</button></form></Modal>}
  </div>;
}
