import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Eye, Package, ShoppingCart, X } from 'lucide-react';
import { api } from '@/services/api';

const money = (v) => `₹${Number(v || 0).toLocaleString('en-IN')}`;
const label = (s) => ({ paid: 'Paid', pending: 'Pending', cancelled: 'Cancelled' }[s] || s || 'Unknown');
const badge = (s) => ({ paid: 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300', pending: 'bg-[#e9c878]/15 text-foreground', cancelled: 'bg-red-500/10 text-red-700 dark:text-red-300' }[s] || 'bg-surface-raised text-muted-foreground');

export default function AdminOrders() {
  const [filter, setFilter] = useState('all');
  const [selected, setSelected] = useState(null);
  const qc = useQueryClient();
  const { data = [], isLoading, error } = useQuery({ queryKey: ['admin-orders'], queryFn: api.admin.orders });
  const cancel = useMutation({ mutationFn: api.admin.cancelOrder, onSuccess: async () => { setSelected(null); await qc.invalidateQueries({ queryKey: ['admin-orders'] }); } });
  const orders = useMemo(() => data.filter((o) => filter === 'all' || o.status === filter), [data, filter]);

  return <div>
    <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">Administration</div><h1 className="display mt-1 text-4xl sm:text-5xl">Orders</h1><p className="mt-2 text-sm text-muted-foreground">Manage customer orders using the existing order and payment statuses.</p></div><div className="flex gap-2"><select value={filter} onChange={(e) => setFilter(e.target.value)} className="input-field"><option value="all">All orders</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="cancelled">Cancelled</option></select></div></div>
    {error && <div className="mt-6 rounded-2xl border border-[#ee9d83]/30 bg-[#ee9d83]/10 p-4 text-sm">{error.message}</div>}
    <div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-3xl border border-border bg-surface p-5"><ShoppingCart className="size-5 text-[#e9c878]" /><div className="mt-4 text-xs uppercase tracking-[.12em] text-muted-foreground">All</div><div className="display mt-2 text-2xl">{data.length}</div></div><div className="rounded-3xl border border-border bg-surface p-5"><Package className="size-5 text-[#e9c878]" /><div className="mt-4 text-xs uppercase tracking-[.12em] text-muted-foreground">Pending</div><div className="display mt-2 text-2xl">{data.filter((o) => o.status === 'pending').length}</div></div><div className="rounded-3xl border border-border bg-surface p-5"><ShoppingCart className="size-5 text-[#e9c878]" /><div className="mt-4 text-xs uppercase tracking-[.12em] text-muted-foreground">Paid</div><div className="display mt-2 text-2xl">{data.filter((o) => o.status === 'paid').length}</div></div></div>
    <div className="mt-6 overflow-hidden rounded-3xl border border-border bg-surface"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-border text-xs uppercase tracking-[.1em] text-muted-foreground"><tr><th className="px-5 py-4">Order</th><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Date</th><th className="px-5 py-4">Items</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Total</th><th className="px-5 py-4"></th></tr></thead><tbody>{isLoading ? <tr><td colSpan="7" className="px-5 py-8 text-muted-foreground">Loading orders…</td></tr> : orders.map((o) => <tr key={o._id} className="border-b border-border last:border-0"><td className="px-5 py-4 font-medium">{o._id?.slice(-8)}</td><td className="px-5 py-4">{o.customerEmail || '—'}</td><td className="px-5 py-4 text-muted-foreground">{o.createdAt ? new Date(o.createdAt).toLocaleDateString('en-IN') : '—'}</td><td className="px-5 py-4">{(o.items || []).reduce((s, i) => s + Number(i.quantity || 0), 0)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${badge(o.status)}`}>{label(o.status)}</span></td><td className="px-5 py-4 font-medium">{money(o.total)}</td><td className="px-5 py-4 text-right"><button type="button" className="btn-ghost" onClick={() => setSelected(o)}><Eye className="size-4" />View</button></td></tr>)}{!isLoading && !orders.length && <tr><td colSpan="7" className="px-5 py-10 text-center text-muted-foreground">No orders found.</td></tr>}</tbody></table></div></div>
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onMouseDown={(e) => { if (e.target === e.currentTarget) setSelected(null); }}><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl border border-border bg-surface p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><div className="eyebrow">Order details</div><h2 className="display mt-1 text-3xl">#{selected._id?.slice(-8)}</h2></div><button type="button" className="btn-ghost" onClick={() => setSelected(null)}><X className="size-4" /></button></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><div><div className="text-xs text-muted-foreground">Customer</div><div className="mt-1">{selected.customerEmail || '—'}</div></div><div><div className="text-xs text-muted-foreground">Status</div><div className="mt-1"><span className={`rounded-full px-2.5 py-1 text-xs ${badge(selected.status)}`}>{label(selected.status)}</span></div></div><div><div className="text-xs text-muted-foreground">Payment</div><div className="mt-1">{selected.payment?.provider || 'Not paid'}{selected.payment?.paidAt ? ` · ${new Date(selected.payment.paidAt).toLocaleString('en-IN')}` : ''}</div></div><div><div className="text-xs text-muted-foreground">Total</div><div className="mt-1 font-medium">{money(selected.total)} {selected.currency || 'INR'}</div></div></div><div className="mt-6"><h3 className="font-semibold">Items</h3><div className="mt-3 divide-y divide-border rounded-2xl border border-border">{(selected.items || []).map((item, i) => <div key={`${item.productId || i}`} className="flex items-center justify-between gap-4 p-4"><div><div className="font-medium">{item.name}</div><div className="text-xs text-muted-foreground">Qty {item.quantity} · {money(item.price)} each</div></div><div className="font-medium">{money(Number(item.price || 0) * Number(item.quantity || 0))}</div></div>)}</div></div>{selected.payment?.razorpayOrderId && <div className="mt-6 rounded-2xl bg-surface-raised p-4 text-xs"><div>Razorpay order: {selected.payment.razorpayOrderId}</div>{selected.payment.razorpayPaymentId && <div className="mt-1">Payment ID: {selected.payment.razorpayPaymentId}</div>}</div>}<div className="mt-6 flex justify-end gap-2">{selected.status === 'pending' && <button type="button" className="btn-ghost" disabled={cancel.isPending} onClick={() => { if (window.confirm('Cancel this pending order?')) cancel.mutate(selected._id); }}>{cancel.isPending ? 'Cancelling…' : 'Cancel order'}</button>}<button type="button" className="btn-primary" onClick={() => setSelected(null)}>Close</button></div>{cancel.error && <div className="mt-3 text-sm text-red-600">{cancel.error.message}</div>}</div></div>}
  </div>;
}
