import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { BarChart3, CalendarDays, CircleDollarSign, Clock3, Package, ShoppingCart, XCircle } from 'lucide-react';
import { api } from '@/services/api';

const money = (value) => `₹${Number(value || 0).toLocaleString('en-IN')}`;

export default function AdminReports() {
  const [days, setDays] = useState('30');
  const { data, isLoading, error } = useQuery({ queryKey: ['admin-reports', days], queryFn: api.admin.reports });
  const topProducts = data?.topProducts || [];
  const byDay = data?.byDay || [];
  const totals = useMemo(() => ({ revenue: byDay.reduce((s, x) => s + Number(x.revenue || 0), 0), orders: byDay.reduce((s, x) => s + Number(x.orders || 0), 0), items: topProducts.reduce((s, x) => s + Number(x.quantity || 0), 0) }), [byDay, topProducts]);
  const visibleDays = days === 'all' ? byDay : byDay.slice(-Number(days));
  const maxRevenue = Math.max(...visibleDays.map((x) => Number(x.revenue || 0)), 1);
  const maxQty = Math.max(...topProducts.map((x) => Number(x.quantity || 0)), 1);

  return <div>
    <div className="flex flex-wrap items-end justify-between gap-4"><div className="flex items-center gap-3"><BarChart3 className="size-5 text-[#e9c878]" /><div><div className="eyebrow">Administration</div><h1 className="display mt-1 text-4xl sm:text-5xl">Reports</h1><p className="mt-2 text-sm text-muted-foreground">A management view of confirmed sales performance and order activity.</p></div></div><div className="flex items-center gap-2"><CalendarDays className="size-4 text-muted-foreground" /><select value={days} onChange={(e) => setDays(e.target.value)} className="input-field"><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="all">All time</option></select></div></div>
    {error && <div className="mt-6 rounded-2xl border border-[#ee9d83]/30 bg-[#ee9d83]/10 p-4 text-sm">{error.message}</div>}
    <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Revenue', totals.revenue, CircleDollarSign, true], ['Paid orders', totals.orders, ShoppingCart, false], ['Items sold', totals.items, Package, false], ['Avg. paid order', totals.orders ? totals.revenue / totals.orders : 0, CircleDollarSign, true]].map(([label, value, Icon, isMoney]) => <div key={label} className="rounded-3xl border border-border bg-surface p-5"><Icon className="size-5 text-[#e9c878]" /><div className="mt-4 text-xs uppercase tracking-[.12em] text-muted-foreground">{label}</div><div className="display mt-2 text-2xl">{isLoading ? '—' : isMoney ? money(value) : Number(value || 0).toLocaleString('en-IN')}</div></div>)}</div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]">
      <section className="rounded-3xl border border-border bg-surface p-6"><h2 className="display text-2xl">Revenue by day</h2><p className="mt-1 text-xs text-muted-foreground">Confirmed paid orders only</p>{isLoading ? <p className="mt-6 text-sm text-muted-foreground">Loading reports…</p> : visibleDays.length ? <div className="mt-6 space-y-3">{visibleDays.map((item) => <div key={item._id}><div className="mb-1 flex justify-between text-xs"><span>{item._id}</span><span>{money(item.revenue)} · {item.orders} orders</span></div><div className="h-2 rounded-full bg-surface-raised"><div className="h-2 rounded-full bg-[#e9c878]" style={{ width: `${Math.max((Number(item.revenue || 0) / maxRevenue) * 100, Number(item.revenue || 0) ? 4 : 0)}%` }} /></div></div>)}</div> : <p className="mt-6 py-8 text-sm text-muted-foreground">No paid sales yet.</p>}</section>
      <section className="rounded-3xl border border-border bg-surface p-6"><h2 className="display text-2xl">Top products</h2><p className="mt-1 text-xs text-muted-foreground">Ranked by revenue</p>{isLoading ? <p className="mt-6 text-sm text-muted-foreground">Loading reports…</p> : topProducts.length ? <div className="mt-6 space-y-4">{topProducts.map((item, index) => <div key={item._id}><div className="flex items-center justify-between gap-3 text-sm"><span className="min-w-0 truncate"><span className="mr-2 text-xs text-muted-foreground">#{index + 1}</span>{item.name || item._id}</span><span className="shrink-0 font-medium">{money(item.revenue)}</span></div><div className="mt-2 h-2 rounded-full bg-surface-raised"><div className="h-2 rounded-full bg-[#e9c878]" style={{ width: `${(Number(item.quantity || 0) / maxQty) * 100}%` }} /></div><div className="mt-1 text-xs text-muted-foreground">{item.quantity} sold</div></div>)}</div> : <p className="mt-6 py-8 text-sm text-muted-foreground">No paid sales yet.</p>}</section>
    </div>
    <section className="mt-6 rounded-3xl border border-border bg-surface p-6"><h2 className="display text-2xl">Daily detail</h2><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-border text-xs uppercase tracking-[.1em] text-muted-foreground"><tr><th className="px-3 py-3">Date</th><th className="px-3 py-3">Paid orders</th><th className="px-3 py-3 text-right">Revenue</th></tr></thead><tbody>{visibleDays.map((item) => <tr key={item._id} className="border-b border-border last:border-0"><td className="px-3 py-3">{item._id}</td><td className="px-3 py-3">{item.orders}</td><td className="px-3 py-3 text-right font-medium">{money(item.revenue)}</td></tr>)}{!isLoading && !visibleDays.length && <tr><td colSpan="3" className="px-3 py-8 text-center text-muted-foreground">No paid sales yet.</td></tr>}</tbody></table></div></section>
    <div className="mt-4 flex flex-wrap gap-3 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><CircleDollarSign className="size-3" /> Revenue counts paid orders only</span><span className="inline-flex items-center gap-1"><Clock3 className="size-3" /> Pending orders are excluded</span><span className="inline-flex items-center gap-1"><XCircle className="size-3" /> Cancelled orders are excluded</span></div>
  </div>;
}
