import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Edit3, Users, X } from 'lucide-react';
import { api } from '@/services/api';

export default function AdminUsers() {
  const queryClient = useQueryClient();
  const { data: users = [], isLoading, error } = useQuery({ queryKey: ['admin-users'], queryFn: api.admin.users });
  const [editing, setEditing] = useState(null);
  const [form, setForm] = useState({ name: '', email: '', role: 'user', isActive: true });
  const update = useMutation({ mutationFn: () => api.admin.updateUser(editing._id, form), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['admin-users'] }); setEditing(null); } });
  const openEdit = user => { setEditing(user); setForm({ name: user.name || '', email: user.email || '', role: user.role || 'user', isActive: user.isActive !== false }); };
  return <div><div className="flex items-center gap-3"><Users className="size-5 text-[#e9c878]" /><div><div className="eyebrow">Administration</div><h1 className="display mt-1 text-4xl">Users</h1></div></div>{error && <div className="mt-6 rounded-2xl border border-[#ee9d83]/30 bg-[#ee9d83]/10 p-4 text-sm">{error.message}</div>}<div className="mt-8 overflow-hidden rounded-3xl border border-border bg-surface"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-border text-xs uppercase tracking-[.1em] text-muted-foreground"><tr><th className="px-5 py-4">Name</th><th className="px-5 py-4">Email</th><th className="px-5 py-4">Role</th><th className="px-5 py-4">Status</th><th className="px-5 py-4" /></tr></thead><tbody>{isLoading ? <tr><td colSpan="5" className="px-5 py-8 text-muted-foreground">Loading users…</td></tr> : users.map(user => <tr key={user._id} className="border-b border-border last:border-0"><td className="px-5 py-4 font-medium">{user.name}</td><td className="px-5 py-4 text-muted-foreground">{user.email}</td><td className="px-5 py-4">{user.role}</td><td className="px-5 py-4">{user.isActive === false ? 'Inactive' : 'Active'}</td><td className="px-5 py-4 text-right"><button type="button" className="btn-ghost" onClick={() => openEdit(user)}><Edit3 className="size-4" /> Edit</button></td></tr>)}</tbody></table></div></div>{editing && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><div className="w-full max-w-lg rounded-3xl border border-border bg-surface p-6"><div className="flex items-center justify-between"><h2 className="display text-2xl">Edit user</h2><button type="button" onClick={() => setEditing(null)}><X className="size-5" /></button></div><div className="mt-6 grid gap-4"><input className="input-field" value={form.name} onChange={e => setForm({...form,name:e.target.value})} placeholder="Name" /><input className="input-field" type="email" value={form.email} onChange={e => setForm({...form,email:e.target.value})} placeholder="Email" /><select className="input-field" value={form.role} onChange={e => setForm({...form,role:e.target.value})}><option value="user">User</option><option value="admin">Admin</option><option value="super_admin">Super Admin</option></select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isActive} onChange={e => setForm({...form,isActive:e.target.checked})} /> Active</label></div><button type="button" disabled={update.isPending} onClick={() => update.mutate()} className="btn-primary mt-6 w-full">{update.isPending ? 'Saving…' : 'Save changes'}</button></div></div>}</div>;
}
